//! Real AAX plugin entry point -- generic across any `gui_host::Processor`,
//! not tied to one plugin's parameter list.
//!
//! AAX's "Describe"/parameter-registration code (`cpp/AaxPlugin_Describe.cpp`,
//! `cpp/AaxPlugin_Parameters.cpp`) is written *once*, here, and reused by
//! every future plugin: at Describe/EffectInit time it queries this crate's
//! FFI surface (`gui_aax_parameter_count`/`_name`/`_default`/`_step_count`,
//! plus the plugin-identity getters generated by [`crate::aax_entry`]) for
//! however many parameters the concrete `Processor` actually has, instead of
//! a plugin hand-writing its own `AAX_CParameter` registration calls. The
//! real-time process callback (`cpp/AaxPlugin_AlgProc.cpp`) does the same:
//! it reads up to [`MAX_PARAMS`] current values out of the AAX packet
//! dispatcher and hands them to `process_block`, which is generic over `P`.
//!
//! `MAX_PARAMS` is a fixed capacity (not a dynamic codegen step) because
//! AAX's real-time context struct (`cpp/AaxPlugin_Alg.h`'s
//! `SAaxGeneric_Alg_Context`) is a plain, compile-time-sized POD -- this
//! crate's C++ files declare `MAX_PARAMS` pointer-sized slots once and reuse
//! them for any processor with that many parameters or fewer. A processor
//! with more than `MAX_PARAMS` parameters would need a larger constant
//! recompiled into both sides (see the `static_assert` in
//! `AaxPlugin_Alg.h`), not a per-plugin file.
//!
//! Each processor built via this bridge is constructed fresh, stack-
//! allocated (never boxed/kept alive across calls): AAX's packet dispatcher
//! already redelivers every parameter's current value on every block, so
//! there's nothing to persist between calls for a processor with no
//! internal state beyond its parameters. A processor with real per-block
//! state (e.g. a filter's delay line) would need AAX's private-data
//! instance-lifecycle (`ResetFieldData`) instead, which this bridge does
//! not implement.
use gui_host::{NormalizedValue, ParameterId, Processor};

/// Fixed capacity for the number of parameters this bridge can expose to
/// AAX. Must match `kAaxGeneric_MaxParams` in `cpp/gui_aax_bridge.h` exactly.
pub const MAX_PARAMS: usize = 16;

pub fn parameter_count<P: Processor>(make_processor: &mut impl FnMut() -> P) -> i32 {
    let processor = make_processor();
    processor.parameters().len().min(MAX_PARAMS) as i32
}

pub fn parameter_id<P: Processor>(make_processor: &mut impl FnMut() -> P, index: i32) -> u32 {
    let processor = make_processor();
    index
        .try_into()
        .ok()
        .and_then(|i: usize| processor.parameters().get(i))
        .map(|p| p.id.0)
        .unwrap_or(0)
}

/// Copies the UTF-8 bytes of parameter `index`'s name into the caller-owned
/// buffer `out` (capacity `out_capacity` bytes), truncating and always
/// NUL-terminating so the C++ side can use it directly as a C string.
/// Returns the number of bytes written, excluding the terminator.
///
/// # Safety
/// `out` must be valid for `out_capacity` writable bytes.
pub unsafe fn parameter_name<P: Processor>(
    make_processor: &mut impl FnMut() -> P,
    index: i32,
    out: *mut u8,
    out_capacity: i32,
) -> i32 {
    if out.is_null() || out_capacity <= 0 {
        return 0;
    }
    let processor = make_processor();
    let name = index
        .try_into()
        .ok()
        .and_then(|i: usize| processor.parameters().get(i))
        .map(|p| p.name)
        .unwrap_or("");

    let capacity = out_capacity as usize;
    let bytes = name.as_bytes();
    let write_len = bytes.len().min(capacity - 1);

    // SAFETY: caller guarantees `out` is valid for `out_capacity` bytes, and
    // `write_len < capacity` leaves room for the NUL terminator below.
    unsafe {
        let out_slice = std::slice::from_raw_parts_mut(out, capacity);
        out_slice[..write_len].copy_from_slice(&bytes[..write_len]);
        out_slice[write_len] = 0;
    }
    write_len as i32
}

pub fn parameter_default<P: Processor>(make_processor: &mut impl FnMut() -> P, index: i32) -> f32 {
    let processor = make_processor();
    index
        .try_into()
        .ok()
        .and_then(|i: usize| processor.parameters().get(i))
        .map(|p| p.default_value.get() as f32)
        .unwrap_or(0.0)
}

/// `0` means continuous (no fixed step count).
pub fn parameter_step_count<P: Processor>(
    make_processor: &mut impl FnMut() -> P,
    index: i32,
) -> i32 {
    let processor = make_processor();
    index
        .try_into()
        .ok()
        .and_then(|i: usize| processor.parameters().get(i))
        .and_then(|p| p.step_count)
        .map(|c| c as i32)
        .unwrap_or(0)
}

/// Applies `values[..num_values]` (in the same order `Processor::parameters()`
/// enumerates them) to a freshly constructed `P`, then processes one mono
/// block in place.
///
/// # Safety
/// `values` must be valid for `num_values` `f32` reads (or null, in which
/// case parameters are left at their defaults). `input` and `output` must
/// each point to at least `num_frames` valid, initialized `f32` samples --
/// the contract AAX's real-time process callback already upholds via
/// `SAaxGeneric_Alg_Context`'s `mInputPP`/`mOutputPP`/`mBufferSize` fields.
pub unsafe fn process_block<P: Processor>(
    mut make_processor: impl FnMut() -> P,
    values: *const f32,
    num_values: i32,
    input: *const f32,
    output: *mut f32,
    num_frames: i32,
) {
    if num_frames <= 0 || input.is_null() || output.is_null() {
        return;
    }
    let num_frames = num_frames as usize;
    let mut processor = make_processor();

    if !values.is_null() && num_values > 0 {
        let mut ids = [ParameterId(0); MAX_PARAMS];
        let param_count = processor.parameters().len().min(MAX_PARAMS);
        for (slot, info) in ids.iter_mut().zip(processor.parameters()) {
            *slot = info.id;
        }

        let n = (num_values as usize).min(param_count);
        // SAFETY: caller guarantees `values` is valid for `num_values` reads.
        let values_slice = unsafe { std::slice::from_raw_parts(values, n) };
        for i in 0..n {
            processor.set_parameter(ids[i], NormalizedValue::new(f64::from(values_slice[i])));
        }
    }

    // SAFETY: caller guarantees `input`/`output` are each valid for
    // `num_frames` samples.
    let input_slice = unsafe { std::slice::from_raw_parts(input, num_frames) };
    let output_slice = unsafe { std::slice::from_raw_parts_mut(output, num_frames) };

    let inputs: [&[f32]; 1] = [input_slice];
    let mut outputs: [&mut [f32]; 1] = [output_slice];
    processor.process(&inputs, &mut outputs);
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TwoParamProcessor {
        a: NormalizedValue,
        b: NormalizedValue,
        parameters: [gui_host::ParameterInfo; 2],
    }

    impl TwoParamProcessor {
        fn new() -> Self {
            Self {
                a: NormalizedValue::new(1.0),
                b: NormalizedValue::new(0.0),
                parameters: [
                    gui_host::ParameterInfo {
                        id: ParameterId(10),
                        name: "A",
                        default_value: NormalizedValue::new(1.0),
                        min_value: NormalizedValue::new(0.0),
                        max_value: NormalizedValue::new(1.0),
                        step_count: None,
                    },
                    gui_host::ParameterInfo {
                        id: ParameterId(20),
                        name: "B",
                        default_value: NormalizedValue::new(0.0),
                        min_value: NormalizedValue::new(0.0),
                        max_value: NormalizedValue::new(1.0),
                        step_count: Some(2),
                    },
                ],
            }
        }
    }

    impl Processor for TwoParamProcessor {
        fn prepare(&mut self, _sample_rate: f64, _max_block_size: usize) {}

        // output = input * a + b, just to prove both parameter slots reach
        // the processor in the right order.
        fn process(&mut self, inputs: &[&[f32]], outputs: &mut [&mut [f32]]) {
            let (a, b) = (self.a.get() as f32, self.b.get() as f32);
            for (input, output) in inputs.iter().zip(outputs.iter_mut()) {
                for (sample_in, sample_out) in input.iter().zip(output.iter_mut()) {
                    *sample_out = sample_in * a + b;
                }
            }
        }

        fn reset(&mut self) {}

        fn channel_layout(&self) -> gui_host::ChannelLayout {
            gui_host::ChannelLayout {
                input_channels: 1,
                output_channels: 1,
            }
        }

        fn parameters(&self) -> &[gui_host::ParameterInfo] {
            &self.parameters
        }

        fn set_parameter(&mut self, id: ParameterId, value: NormalizedValue) {
            match id {
                ParameterId(10) => self.a = value,
                ParameterId(20) => self.b = value,
                _ => {}
            }
        }

        fn parameter_value(&self, id: ParameterId) -> NormalizedValue {
            match id {
                ParameterId(10) => self.a,
                ParameterId(20) => self.b,
                _ => NormalizedValue::new(0.0),
            }
        }
    }

    #[test]
    fn metadata_getters_report_every_parameter() {
        let mut make = TwoParamProcessor::new;
        assert_eq!(parameter_count(&mut make), 2);
        assert_eq!(parameter_id(&mut make, 0), 10);
        assert_eq!(parameter_id(&mut make, 1), 20);
        assert_eq!(parameter_id(&mut make, 2), 0);
        assert_eq!(parameter_default(&mut make, 0), 1.0);
        assert_eq!(parameter_default(&mut make, 1), 0.0);
        assert_eq!(parameter_step_count(&mut make, 0), 0);
        assert_eq!(parameter_step_count(&mut make, 1), 2);

        let mut buf = [0_u8; 8];
        let len = unsafe { parameter_name(&mut make, 1, buf.as_mut_ptr(), buf.len() as i32) };
        assert_eq!(len, 1);
        assert_eq!(&buf[..1], b"B");
        assert_eq!(buf[1], 0);
    }

    #[test]
    fn process_block_applies_values_in_parameter_order() {
        let mut input = [1.0_f32, 1.0, 1.0];
        let mut output = [0.0_f32; 3];
        let values = [0.5_f32, 0.25];

        unsafe {
            process_block(
                TwoParamProcessor::new,
                values.as_ptr(),
                values.len() as i32,
                input.as_ptr(),
                output.as_mut_ptr(),
                input.len() as i32,
            );
        }
        // a=0.5, b=0.25 -> output = 1.0*0.5 + 0.25 = 0.75
        assert_eq!(output, [0.75, 0.75, 0.75]);

        // Null/zero-length values must leave parameters at their defaults
        // (a=1.0, b=0.0) rather than crashing.
        unsafe {
            process_block(
                TwoParamProcessor::new,
                std::ptr::null(),
                0,
                input.as_ptr(),
                output.as_mut_ptr(),
                input.len() as i32,
            );
        }
        assert_eq!(output, [1.0, 1.0, 1.0]);
        let _ = &mut input;
    }
}
