/// The Rust/C++ FFI surface generated by `gui_aax::aax_entry!` for whichever
/// concrete `gui_host::Processor` a plugin project builds. Every function
/// declared here is implemented in Rust; nothing in this crate's C++ files
/// (`AaxPlugin_Describe.cpp`, `AaxPlugin_Parameters.cpp`,
/// `AaxPlugin_AlgProc.cpp`) is specific to one plugin's identity or
/// parameter list -- they all just call through these functions instead.
#pragma once
#ifndef GUI_AAX_BRIDGE_H
#define GUI_AAX_BRIDGE_H

#include <cstdint>

/// Fixed capacity for the number of parameters this bridge can expose to
/// AAX. Must match `gui_aax::component::MAX_PARAMS` in Rust exactly -- both
/// sides size their real-time context/arrays from this one constant.
constexpr int32_t kAaxGeneric_MaxParams = 16;

extern "C" {

// Plugin identity, supplied by whichever plugin invoked `aax_entry!`.
const char* gui_aax_effect_id();
const char* gui_aax_plugin_name();
const char* gui_aax_manufacturer_name();
uint32_t gui_aax_manufacturer_id();
uint32_t gui_aax_product_id();
uint32_t gui_aax_plugin_id_native();

// Parameter metadata, derived automatically from the processor's own
// `gui_host::Processor::parameters()` -- never touched by a plugin project.
int32_t gui_aax_parameter_count();
uint32_t gui_aax_parameter_id(int32_t index);
int32_t gui_aax_parameter_name(int32_t index, char* out, int32_t out_capacity);
float gui_aax_parameter_default(int32_t index);
int32_t gui_aax_parameter_step_count(int32_t index);

// The real-time process bridge: applies `values[0..num_values)` (in the same
// order `gui_aax_parameter_id`/`_name`/etc. enumerate them) to a fresh
// processor instance, then processes one mono block of `num_frames` samples
// from `input` into `output` in place.
void gui_aax_process_block(const float* values, int32_t num_values, const float* input,
                            float* output, int32_t num_frames);

}  // extern "C"

#endif  // GUI_AAX_BRIDGE_H
