/// The Rust/C++ FFI surface generated by `mkapk_aax::aax_entry!` for whichever
/// concrete `mkapk_host::Processor` a plugin project builds. Every function
/// declared here is implemented in Rust; nothing in this crate's C++ files
/// (`AaxPlugin_Describe.cpp`, `AaxPlugin_Parameters.cpp`,
/// `AaxPlugin_AlgProc.cpp`) is specific to one plugin's identity or
/// parameter list -- they all just call through these functions instead.
#pragma once
#ifndef GUI_AAX_BRIDGE_H
#define GUI_AAX_BRIDGE_H

#include <cstdint>

/// Fixed capacity for the number of parameters this bridge can expose to
/// AAX. Must match `mkapk_aax::component::MAX_PARAMS` in Rust exactly -- both
/// sides size their real-time context/arrays from this one constant.
constexpr int32_t kAaxGeneric_MaxParams = 16;

/// Fixed capacity for the number of MIDI channel-voice messages this
/// bridge delivers per real-time block. AAX's own MIDI node buffer can in
/// principle hold more in one block; any excess is simply not read this
/// block (same "generic, fixed-capacity" tradeoff as `kAaxGeneric_MaxParams`).
constexpr int32_t kAaxGeneric_MaxMidiMessages = 32;

extern "C" {

// Plugin identity, supplied by whichever plugin invoked `aax_entry!`.
const char* mkapk_aax_effect_id();
const char* mkapk_aax_plugin_name();
const char* mkapk_aax_manufacturer_name();
uint32_t mkapk_aax_manufacturer_id();
uint32_t mkapk_aax_product_id();
uint32_t mkapk_aax_plugin_id_native();

// Parameter metadata, derived automatically from the processor's own
// `mkapk_host::Processor::parameters()` -- never touched by a plugin project.
int32_t mkapk_aax_parameter_count();
uint32_t mkapk_aax_parameter_id(int32_t index);
int32_t mkapk_aax_parameter_name(int32_t index, char* out, int32_t out_capacity);
float mkapk_aax_parameter_default(int32_t index);
int32_t mkapk_aax_parameter_step_count(int32_t index);

// Whether the processor wants a MIDI input node registered at all (see
// `mkapk_host::Processor::accepts_midi`); returns 0/1 rather than a real
// `bool` to keep this header C-ABI-plain like everything else in it.
int32_t mkapk_aax_accepts_midi();

// The real-time process bridge: applies `values[0..num_values)` (in the same
// order `mkapk_aax_parameter_id`/`_name`/etc. enumerate them) to a fresh
// processor instance, applies up to `num_midi_messages` queued MIDI 1.0
// channel-voice messages (each a `status, data1, data2` byte triple packed
// into `midi_bytes`, unused trailing bytes zero for 2-byte messages), then
// processes one mono block of `num_frames` samples from `input` into
// `output` in place.
void mkapk_aax_process_block(const float* values, int32_t num_values, const uint8_t* midi_bytes,
                            int32_t num_midi_messages, const float* input, float* output,
                            int32_t num_frames);

}  // extern "C"

#endif  // GUI_AAX_BRIDGE_H
