//! Generated by MKIDE's WYSIWYG plugin-UI designer. This is a normal
//! source file once written -- edit it freely; re-running the designer
//! only overwrites it if you ask it to.
use std::cell::Cell;
use std::sync::Arc;

use mkapk_core::{
    CommandList, Event, EventDispatcher, EventResponse, Insetsf, LayoutConstraints,
    LayoutDirection, LayoutEngine, LayoutNode, LayoutResult, MouseEvent, PaintCommand,
    PointerEvent, Rectf, Sizef, TraverseOrder, Tree, Widget, WidgetId, downcast_widget_ref,
};
use mkapk_host::{
    EditorHost, LockFreeParameterGateway, NormalizedValue, ParameterId, ParentWindowHandle,
    PeakMeter, PluginEditor, SizeConstraints,
};
use mkapk_widgets::Theme;

#[cfg(target_os = "macos")]
type ImageRegistry = mkapk_mac::ImageRegistry;
#[cfg(target_os = "macos")]
type TextRegistry = mkapk_mac::TextRegistry;

struct Panel {
    id: WidgetId,
    theme: Theme,
    frame: Cell<Rectf>,
}

impl Panel {
    fn new(theme: Theme) -> Self {
        Self {
            id: WidgetId::new(),
            theme,
            frame: Cell::new(Rectf::default()),
        }
    }
    fn set_frame(&self, frame: Rectf) {
        self.frame.set(frame);
    }
}

impl Widget for Panel {
    fn id(&self) -> WidgetId {
        self.id
    }
    fn layout(&self, _constraints: LayoutConstraints) -> Sizef {
        Sizef::zero()
    }
    fn paint(&self, commands: &mut CommandList) {
        commands.push(PaintCommand::FillRect {
            rect: self.frame.get(),
            color: self.theme.background,
        });
    }
}

pub struct GainEditor {
    view: *mut core::ffi::c_void,
    size: Sizef,
    tree: Tree,
    layout_engine: LayoutEngine,
    layout: LayoutResult,
    gateway: Arc<LockFreeParameterGateway>,
    // Accepted for constructor-signature compatibility with the plugin
    // scaffold's format entry points (`bin/standalone.rs`, VST3/AU/AAX),
    // which all call `Editor::new(gateway, meter)` -- unused here since
    // this design has no peak-meter widget, but kept as a real field
    // (rather than dropped) so it's easy to wire up a meter display later
    // without changing this constructor's signature again.
    #[allow(dead_code)]
    meter: PeakMeter,
    mouse_capture: Option<WidgetId>,
    commands: CommandList,
    #[cfg(target_os = "macos")]
    image_registry: ImageRegistry,
    #[cfg(target_os = "macos")]
    text_registry: TextRegistry,
}

impl GainEditor {
    /// `gateway` should be the same `Arc<LockFreeParameterGateway>` driving
    /// the paired processor's real-time callback.
    pub fn new(gateway: Arc<LockFreeParameterGateway>, meter: PeakMeter) -> Self {
        let theme = Theme::default();
        let mut tree = Tree::new();

        let panel = Panel::new(theme);
        let root = panel.id();
        tree.insert(Box::new(panel), None);

        let mut layout_engine = LayoutEngine::new();
        layout_engine.set_node(LayoutNode {
            id: root,
            direction: LayoutDirection::Column,
            padding: theme.padding,
            ..LayoutNode::default()
        });
        let margin = Insetsf::uniform(4.0);
        for &id in &[] {
            layout_engine.set_node(LayoutNode {
                id,
                margin,
                ..LayoutNode::default()
            });
        }

        let size = Sizef::new(760.0, 600.0);
        let constraints = LayoutConstraints {
            min_width: Some(size.width),
            max_width: Some(size.width),
            min_height: Some(size.height),
            max_height: Some(size.height),
        };
        let layout = layout_engine.compute(&tree, constraints);

        #[cfg(target_os = "macos")]
        let image_registry = ImageRegistry::new();
        #[cfg(target_os = "macos")]
        let text_registry = TextRegistry::new();

        let mut editor = Self {
            view: core::ptr::null_mut(),
            size,
            tree,
            layout_engine,
            layout,
            gateway,
            meter,
            mouse_capture: None,
            commands: CommandList::with_capacity(32),
            #[cfg(target_os = "macos")]
            image_registry,
            #[cfg(target_os = "macos")]
            text_registry,
        };
        editor.apply_layout();
        editor
    }

    fn apply_layout(&mut self) {
        for (&id, layout_box) in self.layout.iter() {
            let Some(node) = self.tree.find(id) else {
                continue;
            };
            let widget = node.widget.borrow();
            let frame = Rectf::new(layout_box.origin, layout_box.size);
            if let Some(panel) = downcast_widget_ref::<Panel>(&**widget) {
                panel.set_frame(frame);
            }
        }
        self.tree.set_layout_result(self.layout.clone());
    }
}

impl PluginEditor for GainEditor {
    fn open(&mut self, parent: ParentWindowHandle, _host: &dyn EditorHost) {
        match parent {
            ParentWindowHandle::Mac(view) => {
                #[cfg(target_os = "macos")]
                {
                    self.view = mkapk_mac::attach_paint_view(view, self.size).unwrap_or(view);
                    let editor_ptr: *mut GainEditor = self;
                    // SAFETY: only dereferenced synchronously from AppKit's
                    // main-thread dispatch of mouse events on the view just
                    // attached above, and never again once `close()` clears
                    // the sink.
                    mkapk_mac::set_input_sink(
                        self.view,
                        Box::new(move |event| {
                            let editor = unsafe { &mut *editor_ptr };
                            match event {
                                Event::MouseDown(e) => editor.on_mouse_down(&e),
                                Event::MouseUp(e) => editor.on_mouse_up(&e),
                                Event::MouseMove(e) => editor.on_mouse_move(&e),
                                _ => EventResponse::Bubble,
                            }
                        }),
                    );
                }
                #[cfg(not(target_os = "macos"))]
                {
                    self.view = view;
                }
            }
            ParentWindowHandle::Windows(view) => {
                self.view = view;
            }
        }
    }

    fn resize(&mut self, size: Sizef) {
        self.size = size;
        let constraints = LayoutConstraints {
            min_width: Some(size.width),
            max_width: Some(size.width),
            min_height: Some(size.height),
            max_height: Some(size.height),
        };
        self.layout = self.layout_engine.compute(&self.tree, constraints);
        self.apply_layout();
        #[cfg(target_os = "macos")]
        mkapk_mac::resize_paint_view(self.view, size);
    }

    fn idle(&mut self) {
        self.commands.clear();
        for id in self.tree.traverse(TraverseOrder::PreOrder) {
            if let Some(node) = self.tree.find(id) {
                node.widget.borrow().paint(&mut self.commands);
            }
        }

        #[cfg(target_os = "macos")]
        {
            let _ = mkapk_mac::update_paint_view(
                self.view,
                self.size,
                1.0,
                &self.commands,
                Some(&self.image_registry),
                Some(&self.text_registry),
            );
        }
    }

    fn close(&mut self) {
        #[cfg(target_os = "macos")]
        mkapk_mac::clear_input_sink(self.view);
    }

    fn on_parameter_changed(&mut self, id: ParameterId, value: NormalizedValue) {
        let _ = (id, value);
    }

    fn size_constraints(&self) -> SizeConstraints {
        SizeConstraints::default()
    }

    fn on_mouse_down(&mut self, event: &MouseEvent) -> EventResponse {
        let mut dispatcher = EventDispatcher::new(&self.tree, &self.layout);
        let target = dispatcher.hit_test(event.position);
        let response = dispatcher.dispatch(Event::MouseDown(event.clone()));
        if response == EventResponse::Handled {
            self.mouse_capture = target;
        }
        response
    }

    fn on_mouse_move(&mut self, event: &PointerEvent) -> EventResponse {
        if self.mouse_capture.is_none() {
            return EventResponse::Bubble;
        }
        let mut dispatcher = EventDispatcher::new(&self.tree, &self.layout);
        dispatcher.set_capture(self.mouse_capture);
        dispatcher.dispatch(Event::MouseMove(event.clone()))
    }

    fn on_mouse_up(&mut self, event: &MouseEvent) -> EventResponse {
        let mut dispatcher = EventDispatcher::new(&self.tree, &self.layout);
        dispatcher.set_capture(self.mouse_capture);
        let response = dispatcher.dispatch(Event::MouseUp(event.clone()));
        self.mouse_capture = None;
        response
    }
}
