/// The Rust/C++ FFI surface generated by `mkapk_vst3::vst3_entry!` for
/// whichever concrete `mkapk_host::Processor` + `mkapk_host::PluginEditor`
/// pair a plugin project builds. Every function declared here is
/// implemented in Rust; nothing in this crate's C++ files (`VstProcessor.cpp`,
/// `VstController.cpp`, `VstView.cpp`, `VstFactory.cpp`) is specific to one
/// plugin's identity or parameter list -- they all just call through these
/// functions instead, mirroring `mkapk-aax`'s `mkapk_aax_bridge.h`.
#pragma once
#ifndef MKAPK_VST3_BRIDGE_H
#define MKAPK_VST3_BRIDGE_H

#include <cstddef>
#include <cstdint>

extern "C" {

// ---- Plugin identity ----------------------------------------------------
const char* mkapk_vst3_plugin_name();
const char* mkapk_vst3_vendor_name();
const char* mkapk_vst3_url();
const char* mkapk_vst3_email();
const char* mkapk_vst3_version();
/// Each returns a pointer to 16 bytes (a VST3 `TUID`).
const uint8_t* mkapk_vst3_processor_cid();
const uint8_t* mkapk_vst3_controller_cid();

// ---- Bus layout, derived from `Processor::channel_layout()`/`accepts_midi()` ----
uint32_t mkapk_vst3_input_channels();
uint32_t mkapk_vst3_output_channels();
int32_t mkapk_vst3_accepts_midi();

// ---- Parameter metadata, derived from `Processor::parameters()` ----------
int32_t mkapk_vst3_parameter_count();
uint32_t mkapk_vst3_parameter_id(int32_t index);
/// Writes `out_capacity` UTF-16 code units (including a trailing NUL) of
/// the parameter's display name into `out`; returns the unit count written,
/// or -1 if `index` is out of range.
int32_t mkapk_vst3_parameter_name(int32_t index, char16_t* out, int32_t out_capacity);
double mkapk_vst3_parameter_default(int32_t index);
int32_t mkapk_vst3_parameter_step_count(int32_t index);

/// Looks a MIDI CC number up in the plugin's `midi_cc_map`; returns 1 and
/// writes the mapped parameter ID to `out_param_id`, or returns 0 if this
/// CC has no mapped parameter.
int32_t mkapk_vst3_midi_cc_to_param(int32_t midi_cc_number, uint32_t* out_param_id);

// ---- Processor lifecycle -------------------------------------------------
// Each `handle` is an opaque pointer to a fresh, boxed `dyn Processor`; one
// per `VstProcessor` C++ instance, exactly matching a real host's
// one-`IComponent`-per-plugin-instance lifetime.
void* mkapk_vst3_processor_create();
void mkapk_vst3_processor_destroy(void* handle);
void mkapk_vst3_processor_prepare(void* handle, double sample_rate, int32_t max_samples_per_block);
void mkapk_vst3_processor_set_parameter(void* handle, uint32_t param_id, double normalized_value);
double mkapk_vst3_processor_get_parameter(void* handle, uint32_t param_id);
/// `status`/`data1`/`data2` are one MIDI 1.0 channel-voice message's raw
/// bytes (unused trailing byte 0 for 2-byte messages).
void mkapk_vst3_processor_handle_midi(void* handle, uint8_t status, uint8_t data1, uint8_t data2);
/// `inputs`/`outputs` are arrays of `num_inputs`/`num_outputs` raw `float*`
/// channel buffers, each valid for `num_frames` samples.
void mkapk_vst3_processor_process(void* handle, const float* const* inputs, int32_t num_inputs,
                                   float* const* outputs, int32_t num_outputs, int32_t num_frames);

// ---- Editor lifecycle -----------------------------------------------------
// One `handle` per `VstEditorView` C++ instance -- lazily created once by
// `VstController::createView`, matching `IEditController::create_view`'s
// "only one view per controller" contract in the current Rust
// implementation.
void* mkapk_vst3_editor_create();
void mkapk_vst3_editor_destroy(void* handle);
/// `parent` is the native parent view/window handle (`NSView*`/`HWND`).
void mkapk_vst3_editor_open(void* handle, void* parent);
void mkapk_vst3_editor_close(void* handle);
void mkapk_vst3_editor_get_size(void* handle, float* out_width, float* out_height);
void mkapk_vst3_editor_resize(void* handle, float width, float height);
void mkapk_vst3_editor_idle(void* handle);
void mkapk_vst3_editor_parameter_changed(void* handle, uint32_t param_id, double normalized_value);

// ---- Host callbacks: the shim holds the real host pointers as C++ state
// and exposes these small wrappers so Rust never needs to know VST3's COM
// vtable layout for the *host*-supplied interfaces (`IComponentHandler`,
// `IPlugFrame`) -- avoids a second FFI paradigm (e.g. `cxx`) for the one
// direction the plugin calls out instead of being called into.
// `host_context` is whatever `mkapk_vst3_editor_set_host_context` was given;
// opaque to Rust.
typedef void (*mkapk_vst3_begin_edit_fn)(void* host_context, uint32_t param_id);
typedef void (*mkapk_vst3_perform_edit_fn)(void* host_context, uint32_t param_id, double value);
typedef void (*mkapk_vst3_end_edit_fn)(void* host_context, uint32_t param_id);
typedef void (*mkapk_vst3_resize_view_fn)(void* host_context, float width, float height);

void mkapk_vst3_editor_set_host_context(void* handle, void* host_context,
                                         mkapk_vst3_begin_edit_fn begin_edit,
                                         mkapk_vst3_perform_edit_fn perform_edit,
                                         mkapk_vst3_end_edit_fn end_edit,
                                         mkapk_vst3_resize_view_fn resize_view);

}  // extern "C"

#endif  // MKAPK_VST3_BRIDGE_H
